# Override containers for local / dev environment
version: "2.4"
services:
  ui:
    ports:
      - "3000:3000"
    stdin_open: true
    build:
      context: ui
      dockerfile: Dockerfile.dev
    env_file: ./ui/.env
    volumes:
      - ./ui:/app #Allows source folders to be watched

  server:
    ports:
      - "3001:3001"
    volumes:
      - ./server/src:/app/src # Allows source folders to be watched
      - ./server/config:/app/config
      - projet3_server_data:/data
    environment:
      - projet3_ENV=local

  mongodb:
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - projet3_mongodb_data:/data

volumes:
  projet3_mongodb_data:
    driver: local
    name: projet3_mongodb_data
  projet3_server_data:
    driver: local
    name: projet3_server_data
