FROM node:16.13.1-alpine

ARG REACT_APP_API_URL

ENV REACT_APP_API_URL=$REACT_APP_API_URL


WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY ./ /app

EXPOSE 3000
CMD yarn start